-- Phase 4: 报表统计 + 审计日志增强
-- NOTE: biz_report_snapshot table is already created in V1__init_schema.sql
-- NOTE: sys_audit_log.target_type column is already created in V1__init_schema.sql
-- No additional DDL changes needed for Phase 4.
